FROM node:18

WORKDIR /app

COPY ./index.js ./index.js
COPY ./models ./models
COPY ./middleware ./middleware
COPY ./routes ./routes
COPY ./utilities ./utilities
COPY ./package.json ./package.json
COPY ./env ./env

RUN npm install

EXPOSE 6969

CMD ["node", "index.js"]